FROM golang:alpine as builder

RUN mkdir /build
ADD . /build/
WORKDIR /build

RUN CGO_ENABLED=0 go build -o ops-control ./cmd/main.go

FROM docker.io/envoyproxy/envoy:v1.24-latest

LABEL "organization.name"="upper-institute"
LABEL "organization.repository"="ops-control"
LABEL "repository.application"="front-proxy"

COPY --from=builder /build/ops-control /usr/local/bin/

WORKDIR /etc/envoy/
COPY container/front-proxy/envoy.yaml ./
COPY container/front-proxy/docker-entrypoint.sh ./

ENTRYPOINT ["/etc/envoy/docker-entrypoint.sh"]

CMD ["envoy", "-l", "info",  "-c", "/etc/envoy/envoy.rendered.yaml"]
