FROM golang:alpine as builder

RUN mkdir /build
ADD . /build/
WORKDIR /build

RUN CGO_ENABLED=0 go build -o hike ./cmd/main.go

FROM docker.io/envoyproxy/envoy:v1.24-latest

LABEL "organization.name"="upper-institute"
LABEL "organization.repository"="hike"
LABEL "repository.application"="proxy"

COPY --from=builder /build/hike /usr/local/bin/

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates

WORKDIR /etc/envoy/
COPY container/proxy/envoy.yaml ./
COPY container/proxy/docker-entrypoint.sh ./

USER root

COPY server.key ./
COPY server.crt ./

RUN chown envoy:envoy server.key server.crt

USER envoy

ENTRYPOINT ["/etc/envoy/docker-entrypoint.sh"]

CMD ["envoy", "-l", "info",  "-c", "/etc/envoy/envoy.yaml"]
