FROM golang:alpine as builder

RUN mkdir /build
ADD . /build/
WORKDIR /build

RUN CGO_ENABLED=0 go build -o hike ./cmd/main.go

FROM debian:bookworm

LABEL "organization.name"="upper-institute"
LABEL "organization.repository"="hike"
LABEL "repository.application"="hike"

COPY --from=builder /build/hike /usr/local/bin/

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates

WORKDIR /etc/hike/

COPY server.key ./
COPY server.crt ./

RUN groupadd -r hike && useradd -r -g hike hike

RUN chown hike:hike server.key server.crt

USER hike

CMD ["hike", "-h"]

